@hostname=http://localhost:3000

### DAFTARKAN USER
POST {{hostname}}/registrasi HTTP/1.1
Content-Type: application/json

{
  "fullName" :"cr4r",
  "email":"cr4r@gmail.com",
  "password" : "123"
}

### LOGIN USER
POST {{hostname}}/login HTTP/1.1
Content-Type: application/json

{
  "email":"cr4r@gmail.com",
  "password" : "123"
}

### Refresh Token
POST {{hostname}}/user/refresh HTTP/1.1
Content-Type: application/json

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWQ5ZTE3YjVhMmRlODBkY2I4YWMzMCIsImp0aSI6ImZmN2YxN2I1LWQ5NTgtNGNmOS05MjIwLWE2MTAwYjgxMjg2ZCIsImlzcyI6ImNvZGVycy5mYW1pbHkuYXBpIiwiYXVkIjoiY29kZXJzLmZhbWlseS5hcHAiLCJpYXQiOjE3NDY4ODcyNjgsImV4cCI6MTc0NzQ5MjA2OH0.kHGjF1jir5jD63qW9tNwAc-bWM9rfFEFUcecA7SfEaM"
}

### Logout Token
POST {{hostname}}/user/logout HTTP/1.1
Content-Type: application/json

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWQ5ZTE3YjVhMmRlODBkY2I4YWMzMCIsImp0aSI6ImZmN2YxN2I1LWQ5NTgtNGNmOS05MjIwLWE2MTAwYjgxMjg2ZCIsImlzcyI6ImNvZGVycy5mYW1pbHkuYXBpIiwiYXVkIjoiY29kZXJzLmZhbWlseS5hcHAiLCJpYXQiOjE3NDY4ODcyNjgsImV4cCI6MTc0NzQ5MjA2OH0.kHGjF1jir5jD63qW9tNwAc-bWM9rfFEFUcecA7SfEaM"
}