@hostname=http://localhost:3000

### DAFTARKAN USER
POST {{hostname}}/registrasi HTTP/1.1
Content-Type: application/json

{
  "fullName" :"cr4r",
  "email":"cr4r@gmail.com",
  "password" : "123"
}

### DAFTARKAN USER
POST {{hostname}}/login HTTP/1.1
Content-Type: application/json

{
  "fullName" :"cr4r",
  "email":"cr4r@gmail.com",
  "password" : "123"
}